### ISSUE TITLE
Votes not working for everyone

### ISSUE THREAD

**Issue by kuccello** [nko/website#1]
I have reports from some friends and family members that they were unable to vote for my app:

Here is one excerpt:

Maria Uccello: ok so I tried to vote, the site requested my email. I entered it and it still did not go through you might want to look into that. I would hate that you are missing out on votes.
18 hours ago · Like · 

I had a few other comment that it was not working for them either. Is there a browser dependency issue? JS?

**Comment by visnup** [comment]
there's definitely a js dependency issue. we've tested voting in firefox, safari, and chrome. we think it may not work on IE8, which we were going to look into tonight.

**Comment by visnup** [comment]
I've done some work on blatant IE bugs. I'm hoping that was the problem your friends were seeing.

**Comment by visnup** [comment]
could you please ask some of them to try again and see how it goes? again, sorry for all of the woes.

**Comment by kuccello** [comment]
Will do - I'll let you know what they say

**Comment by kuccello** [comment]
seems to be working for them now - thanks
